FROM amd64/ubuntu:18.04
RUN /bin/bash -c 'apt-get update && \
    apt-get install -y python gcc g++ gfortran \
    gcc-aarch64-linux-gnu \
    g++-aarch64-linux-gnu \
    gfortran-aarch64-linux-gnu \
    pkg-config libglibmm-2.4-dev libpixman-1-dev cmake wget'
